AutoPrintModel/Card.h
AutoPrintModel/Customer.h
AutoPrintModel/File.h
AutoPrintModel/Location.h
AutoPrintModel/Order.h
AutoPrintModel/Payment_Methods.h
AutoPrintModel/Printer.h
AutoPrintModel/User.h
AutoPrintModel/Wallet.h

Propertys hechos - Ricardo

---

AutoPrintModel/Card.h
AutoPrintModel/Customer.h
AutoPrintModel/File.h
AutoPrintModel/Location.h
AutoPrintModel/Order.h
AutoPrintModel/Payment_Methods.h
AutoPrintModel/Printer.h
AutoPrintModel/Wallet.h

Ya les cambie los propertys tipo baldeon

Propertys baldeon

---

AutoPrintModel/Order.h

cambio en price (demostrativo)

---

AutoPrintView/AutoPrintView.vcxproj
AutoPrintView/PrintMainForm.h
AutoPrintView/PrintMainForm.resx

ACTUALIZACIÓN

---

AutoPrintView/AutoPrintView.vcxproj
AutoPrintView/AutoPrintView.vcxproj.filters
AutoPrintView/PrintForm.cpp
AutoPrintView/PrintForm.h
AutoPrintView/PrintForm.resx
AutoPrintView/PrintMainForm.h
AutoPrintView/UserTableForm.cpp
AutoPrintView/UserTableForm.h
AutoPrintView/UserTableForm.resx

Interfaces secundarias e interfaz de mantenimiento de usuario

Interfaces secundarias y usuarios

---

AutoPrintView/UserTableForm.h

2da actualización

---

AutoPrintView/AutoPrintView.vcxproj
AutoPrintView/AutoPrintView.vcxproj.filters
AutoPrintView/CardVISAForm.cpp
AutoPrintView/CardVISAForm.h
AutoPrintView/LoginForm.h
AutoPrintView/LoginForm.resx
AutoPrintView/PrintForm.h
AutoPrintView/PrintMainForm.h
AutoPrintView/UserForm.h
AutoPrintView/UserForm.resx
AutoPrintView/WalletForm.cpp
AutoPrintView/WalletForm.h
AutoPrintView/WalletForm.resx

Solo interfaces, Inicio, registro y PrintMainForm

Full modificaciones, Gaaaaaaaaa

---

AutoPrintView/Inicio.h
AutoPrintView/LoginForm.h
AutoPrintView/LoginForm.resx
AutoPrintView/PrintForm.h
AutoPrintView/UserForm.h
AutoPrintView/UserForm.resx

Interfaz como lo pidió el diseñador

Código Hermoso

---

AutoPrintView/AutoPrintView.vcxproj
AutoPrintView/CardVISAForm.h
AutoPrintView/CardVISAForm.resx

CardVisaForm

---

AutoPrintController/AutoPrintController.cpp
AutoPrintController/AutoPrintController.h
AutoPrintModel/Order.h
AutoPrintPersistance/AutoPrintPersistance.cpp
AutoPrintPersistance/AutoPrintPersistance.h
AutoPrintView/Inicio.h
AutoPrintView/LoginForm.h
AutoPrintView/PrintForm.h
AutoPrintView/PrintForm.resx
AutoPrintView/UserForm.h

Orden en el Controller y Persistance

---

AutoPrintController/AutoPrintController.cpp
AutoPrintController/AutoPrintController.h
AutoPrintPersistance/AutoPrintPersistance.cpp
AutoPrintPersistance/AutoPrintPersistance.h
AutoPrintView/PrintForm.h
AutoPrintView/PrintForm.resx
AutoPrintView/PrintMainForm.h

Mi pequeño gran avance

---

AutoPrintController/AutoPrintController.h
AutoPrintView/LoginForm.h
AutoPrintView/PrintMainForm.h
AutoPrintView/UserTableForm.h
AutoPrintView/UserTableForm.resx

Mantenimiento terminado faltta compilar porque no se podia:"v

Mantenimiento confirmado

---

AutoPrintView/AutoPrintView.cpp
AutoPrintView/WalletForm.h

Edición de la Billetera

---

AutoPrintView/AutoPrintView.cpp

cambio en el archivo include e inicio para el view

cambio en el archivo include e inicio para el view

---

AutoPrintController/AutoPrintController.cpp
AutoPrintController/AutoPrintController.h

Casi terminado

---

AutoPrintModel/Order.h
AutoPrintView/PrintForm.h
AutoPrintView/PrintForm.resx
AutoPrintView/PrintMainForm.h

ultimo LC3

---

AutoPrintView/LoginForm.h
AutoPrintView/MyProfile.h
AutoPrintView/UserTableForm.h
AutoPrintView/Users.xml

El usuario ya puede modificar sus datos

MiPerfil ya se puede actualizar

---

AutoPrintView/CardVISAForm.h

CardVisaForm validando datos completos.

card visa ezzz

---

AutoPrintModel/Order.h
AutoPrintView/PrintForm.h

Historial de archivos personal

historial personal

---

AutoPrintView/CardVISAForm.h
AutoPrintView/PrintForm.h

Hay probabilidad del 20% que salga un mensaje de atasco antes de imprimir en pago por tarjeta o por billetera

chance de 2 a 10 (de 1 a 10 es bien yuca xd)

---

AutoPrintController/AutoPrintController.cpp
AutoPrintController/AutoPrintController.h
AutoPrintPersistance/AutoPrintPersistance.cpp
AutoPrintPersistance/AutoPrintPersistance.h
AutoPrintView/AutoPrintView.vcxproj
AutoPrintView/AutoPrintView.vcxproj.filters
AutoPrintView/Empleados.cpp
AutoPrintView/Empleados.h
AutoPrintView/PrintMainForm.h
ScriptSQL/ScriptBD.sql

Sql de empleados y su mantenimiento

---

AutoPrintView/PrintForm.h

Historial archivos ver xddd

---

AutoPrintView/OrdenForm.h
AutoPrintView/PrintMainForm.h

El empleado, además del customer, recibirá esporádicamente avisos que la impresora se atascó, de modo que una vez dándole OK el programa continúa.

Empleado recibe notificaciones de atasco (simuladas)

---

AutoPrintController/AutoPrintController.cpp
AutoPrintController/AutoPrintController.h
AutoPrintView/OrdenForm.h
AutoPrintView/OrdenForm.resx

Implementación adicional de Arduino

---

AutoPrintController/AutoPrintController.cpp
AutoPrintView/OrdenForm.h

Implementación de arduino: Envio de lista 1, falta el envío de lista 2.

Implementación de arduino: Envio de lista 1, falta el envío de lista 2.
